inherit_from: .rubocop_todo.yml

Metrics/MethodLength:
  Max: 7
  Exclude:
    - 'bin/bundle'
    - 'db/migrate/*'

Style/Documentation:
  Enabled: false

#disable nested module/class definitions 
Style/ClassAndModuleChildren:
  Enabled: 
  
Style/IfUnlessModifier:
  Enabled: false